// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class CatchResources
{
        public const string achievement_25_punten_wtf = "CgkIqaSYpNwIEAIQBQ"; // <GPGSID>
        public const string leaderboard_highscore = "CgkIqaSYpNwIEAIQBg"; // <GPGSID>
        public const string achievement_15_punten_nice = "CgkIqaSYpNwIEAIQAw"; // <GPGSID>
        public const string achievement_10_punten_woah = "CgkIqaSYpNwIEAIQAg"; // <GPGSID>
        public const string achievement_grutto_gas = "CgkIqaSYpNwIEAIQBw"; // <GPGSID>
        public const string achievement_20_punten_easy = "CgkIqaSYpNwIEAIQBA"; // <GPGSID>
        public const string achievement_5_punten_maar = "CgkIqaSYpNwIEAIQAQ"; // <GPGSID>

}

